[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Disable automatic blobs feature
[functions]
  included_files = ["!node_modules/**/*"]

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Headers for all pages - ensure indexing is allowed
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    # Ensure no noindex headers
    X-Robots-Tag = "index, follow"

# Headers for images
[[headers]]
  for = "/:all*(svg|jpg|jpeg|png|webp|gif|ico)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Thu, 31 Dec 2025 23:59:59 GMT"

# Disable Netlify image optimization redirects to use Next.js built-in optimization
# [[redirects]]
#   from = "/_next/image"
#   to = "/.netlify/images"
#   status = 200
#   
# [[redirects]]
#   from = "/_ipx/*"
#   to = "/.netlify/images"
#   status = 200

# Force HTTPS redirect - remove www redirects
[[redirects]]
  from = "http://dusungrenggeng.netlify.app/*"
  to = "https://dusungrenggeng.netlify.app/:splat"
  status = 301
  force = true
